language: objective-c
branches:
    only:
        - master
before_install:
    - brew update
    - brew uninstall xctool
    - brew install xctool
    - bundle install --path .bundle
before_script:
    - bundle exec rake -s analyze
script: bundle exec rake -s test
after_success:
    - bundle exec rake -s coveralls:mac
